package no.uio.ifi.in2000.vaeraktiv.utils

val weatherDescriptions = mapOf(
    "clearsky" to "Klar himmel",
    "partlycloudy" to "Delvis skyet",
    "cloudy" to "Overskyet",
    "fair" to "Pent vær",
    "fog" to "Tåke",
    "rainshowers" to "Regnbyger",
    "heavyrainshowers" to "Kraftige regnbyger",
    "snowshowers" to "Snøbyger",
    "heavysnowshowers" to "Kraftige snøbyger",
    "rain" to "Regn",
    "heavyrain" to "Kraftig regn",
    "snow" to "Snø",
    "heavysnow" to "Kraftig snø",
    "sleet" to "Sludd",
    "thunderstorm" to "Tordenvær",
    "rainandthunder" to "Regn og torden",
    "snowandthunder" to "Snø og torden",
    "sleetandthunder" to "Sludd og torden",
    "heavyrainandthunder" to "Kraftig regn og torden",
    "lightrain" to "Lett regn",
    "lightrainshowers" to "Lette regnbyger",
    "lightrainshowersandthunder" to "Lette regnbyger og torden",
    "lightsleet" to "Lett sludd",
    "lightsleetandthunder" to "Lett sludd og torden",
    "lightsleetshowers" to "Lette sluddbyger",
    "lightsnow" to "Lett snø",
    "lightsnowandthunder" to "Lett snø og torden",
    "lightsnowshowers" to "Lette snøbyger",
    "lightsleetshowersandthunder" to "Lette sluddbyger og torden",
    "lightsnowshowersandthunder" to "Lette snøbyger og torden",
    "rainshowersandthunder" to "Regnbyger og torden",
    "sleetshowers" to "Sluddbyger",
    "sleetshowersandthunder" to "Sluddbyger og torden",
    "snowshowersandthunder" to "Snøbyger og torden",
    "heavysnowshowersandthunder" to "Kraftige snøbyger og torden",
    "heavysnowandthunder" to "Kraftig snø og torden",
    "heavysleetshowersandthunder" to "Kraftige sluddbyger og torden",
    "heavysleetshowers" to "Kraftige sluddbyger",
    "heavysleetandthunder" to "Kraftig sludd og torden",
    "heavysleet" to "Kraftig sludd",
    "heavyrainshowersandthunder" to "Kraftige regnbyger og torden"
)